### PR TITLE
[close #2] Tab to spaces

### LINKED ISSUE #2: Tabs versus spaces
First, i love this library. You are amazing and this is great. I just had a conversation with someone the other day about writing something like this, and here it is already written!

Minor question/nit. I was looking through the internals, they're very clean. I was however wondering if we could switch from tabs to 2 spaces instead? It's not a requirement by any stretch, but 2 spaces seems to be the community norm and as you start getting contributions you'll likely end up with a miss-mash of tabs and spaces.

Would you accept a pull request that converted all the tabs to 2 spaces?

### PR DESCRIPTION
**Pull request by schneems**

### CODE REVIEW

**Comment by ioquatix** [comment]
Thanks!

**Comment by schneems** [comment]
Thanks again for this gem

**Comment by ioquatix** [comment]
I think too often people are not careful with code. The more time I spend in open source, the more I come to realise we are all human, and sometimes we overlook things. Our environments should support us not to overlook things which may eventually hurt us. `rack-freeze` was designed to try and support developers making better code. Better code, where the alternative is tangibly worse.

**Comment by ioquatix** [comment]
Fixes https://github.com/ioquatix/rack-freeze/issues/2 for reference.

**Comment by ioquatix** [comment]
@schneems I'm not trying to be passive aggressive here with the references, and updates, just keeping tabs on the conversion. As I said, if things change for the better, I'll eat my own hat :)

**Pull request merged**
